### PR TITLE
support for prefetch links to JavaScript resource

### PR DESCRIPTION
**Pull request by ppitonak**

### CODE REVIEW

**Comment by pgilad** [comment]
Hey thanks for the PR, great idea!
Just 1 question - isn't link prefetch with `href` attribute and not `src`, i.e:
`<link rel="prefetch" href="/images/big.jpeg">`

(according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ)

**Comment by ppitonak** [comment]
Oooops... you are right. What would be the best way to implement it?

**Comment by pgilad** [comment]
Can a prefetch link also be either js or css?

**Comment by ppitonak** [comment]
Yes, AFAIK it can be almost anything

```
<link rel="prefetch" href="/images/big.jpeg">
<link rel="prefetch" href="/styles/my.css">
<link rel="prefetch" href="/scripts/my.js">
<link rel="prefetch" href="http://example.org/scripts/my.js">
<link rel="prefetch" href="http://example.org/blog/article?id=45">
```

**Comment by pgilad** [comment]
Ok, currently we only handle js/css assets. I have an idea how to incorporate it.

**Comment by pgilad** [comment]
Thanks - merged via c5b3487524a5bb9d28a7ef9a8944522cbe5def58

**Pull request merged**
